[package]
name = "swiftcut_backend"
version = "1.0.0"
edition = "2025"

[lib]
name = "swiftcut_backend"
path = "jni.rs"
crate-type = ["cdylib"]

[dependencies]
jni = "0.21"
ffmpeg-next = { version = "6.1", features = ["build"] }
