
name: Java CI with Gradle

on:
  workflow_dispatch:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: recursive


    - name: Setup Gradle Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-android-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-android-

    - name: Setup Cargo Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          app/src/main/backend/target/aarch64-linux-android
        key: ${{ runner.os }}-rust-${{ hashFiles('app/src/main/backend/Cargo.toml') }}-arm64
        restore-keys: |
          ${{ runner.os }}-rust-
            
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Decode Keystore
      env:
        KEYSTORE_ENCODED: ${{ secrets.KEYSTORE }}
      run: | 
        echo "$KEYSTORE_ENCODED" | base64 --decode > ${{ github.workspace }}/app/ks.jks

    - name: Build
      env: 
        KEYSTORE_PATH: "ks.jks"
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
      run: |
        chmod +x ./gradlew && ./gradlew assembleRelease
        ls app/src/main/jniLibs/arm64-v8a/
  
    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: swiftCut-build
        path: |
          app/build/outputs/apk/release/swiftCut-release.apk
